{
 "title": "CDC Onprem Resources Timeseries",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "Account ID",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\"},account_id)"
    }
   },
   {
    "name": "ophid",
    "label": "OPHID",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\", account_id=~\"$account_id\"},ophid)"
    }
   },
   { "name": "threshold", "label": "Threshold %", "query": "1,50,70,90" }
  ]
 },
 "panels": [
  {
   "title": "CDC Onprem Memory Usage (>$threshold%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "clamp_min(\n  (onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) /\n  (onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) *100 > $threshold, 0\n)",
     "legendFormat": "{{ophid}}"
    }
   ]
  },
  {
   "title": "CDC Onprem CPU Usage (>$threshold%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "clamp_min(\n  (onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) > $threshold, 0\n)",
     "legendFormat": "{{ophid}}"
    }
   ]
  },
  {
   "title": "CDC Onprem Volume Usage (>$threshold%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "clamp_min(\n  (onprem_cdc_volume_used_percent{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) > $threshold, 0\n)",
     "legendFormat": "{{ophid}} - {{device}}"
    }
   ]
  },
  {
   "title": "CDC Onprem Memory Usage Alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) / \n  (onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) * 100",
     "legendFormat": "{{ophid}}"
    }
   ]
  },
  {
   "title": "CDC Onprem CPU Usage Alert",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "(onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})",
     "legendFormat": "{{ophid}}"
    }
   ]
  },
  {
   "title": "CDC Onprem Volume Usage Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "(onprem_cdc_volume_used_percent{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})",
     "legendFormat": "{{ophid}} - {{device}}"
    }
   ]
  }
 ]
}