{
 "title": "CDC OnPrem Log",
 "tags": [
  "cdc",
  "logging",
  "monitoring",
  "table"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CDC Error Logs Summary",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(500, sum by (agentId, containerId) (count_over_time({containerId=~\"cdc_.*\"} |= \"error\" [15m])))"
    }
   ]
  },
  {
   "title": "Top 50 Error Rate Increase",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(50, sum by (accountId, agentId, containerId) (rate({containerId=~\"cdc_.*\"} |= \"error\" [5m])) * 60)"
    }
   ]
  },
  {
   "title": "Account Information",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "group by (account_id, account_name) (atcapi_account_objects2)"
    }
   ]
  }
 ]
}