{
 "title": "CDC Onprem Resources Alert",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10m",
 "panels": [
  {
   "title": "CDC Onprem Memory Usage Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  onprem_host_memory_usage_used{} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}\n) / (\n  onprem_host_memory_usage_total{} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}\n) * 100",
     "legendFormat": "{{ophid}} - {{service}}"
    }
   ]
  },
  {
   "title": "CDC Onprem CPU Usage Alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "onprem_cpu_percentage{} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}",
     "legendFormat": "{{ophid}} - {{service}}"
    }
   ]
  },
  {
   "title": "CDC Onprem Volume Usage Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "onprem_cdc_volume_used_percent{} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}",
     "legendFormat": "{{ophid}} - {{device}} - {{service}}"
    }
   ]
  }
 ]
}