{
 "title": "CDC Onprem Flow Status Timeseries",
 "tags": [
  "cdc",
  "flow-status"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "Account ID",
    "query": {
     "query": "label_values(cdc_flow_status,account_id)"
    }
   },
   {
    "name": "flow_id",
    "label": "Flow ID",
    "query": {
     "query": "label_values(cdc_flow_status{account_id=~\"$account_id\"},flow_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CDC Onprem Flow Status Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Current Flow Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cdc_flow_status{account_id=~\"$account_id\", flow_id=~\"$flow_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Flows by Account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(account_id) (cdc_flow_status{account_id=~\"$account_id\", flow_id=~\"$flow_id\"})",
     "legendFormat": "Flows for Account {{account_id}}",
     "minInterval": "10m"
    }
   ]
  },
  {
   "title": "Flow Status Summary",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cdc_flow_status{account_id=~\"$account_id\", flow_id=~\"$flow_id\"})",
     "legendFormat": "Total Flows"
    },
    {
     "expr": "count(cdc_flow_status{account_id=~\"$account_id\", flow_id=~\"$flow_id\"} == 1) or vector(0)",
     "legendFormat": "Active Flows"
    },
    {
     "expr": "count(cdc_flow_status{account_id=~\"$account_id\", flow_id=~\"$flow_id\"} == 0.5) or vector(0)",
     "legendFormat": "Pending Flows"
    },
    {
     "expr": "count(cdc_flow_status{account_id=~\"$account_id\", flow_id=~\"$flow_id\"} == 0) or vector(0)",
     "legendFormat": "Review Details"
    }
   ]
  },
  {
   "title": "CDC Flow Status Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(cdc_flow_status == 0)", "minInterval": "5m" }
   ]
  }
 ]
}