{
 "title": "CDC QPS",
 "tags": [
  "cdc",
  "onprem"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OphID",
    "label": "Select OphID",
    "query": {
     "query": "label_values(onprem_cdc_received_events_from_bloxone,ophid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 CDC Customers with RPM/Ophid",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid) (\n    increase(\n      {__name__=~\"onprem_cdc_received_events_from_bloxone|onprem_cdc_received_events_from_nios\", ophid=~\"$OphID\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid) (\n    increase(\n      {__name__=~\"onprem_cdc_received_events_from_bloxone|onprem_cdc_received_events_from_nios\", ophid=~\"$OphID\"}[$__range]\n    )\n  ) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 CDC Customers with RPM/ Account",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (account_id) (\n    increase(\n      {__name__=~\"onprem_cdc_received_events_from_bloxone|onprem_cdc_received_events_from_nios\"}[$__range]\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(\n  10,\n  sum by (account_id) (\n    increase(\n      {__name__=~\"onprem_cdc_received_events_from_bloxone|onprem_cdc_received_events_from_nios\"}[$__range]\n    )\n  ) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10  CDC customer RPM NIOS per Ophid ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid) (increase(onprem_cdc_received_events_from_nios{ophid=~\"$OphID\"}[$__range]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid) (increase(onprem_cdc_received_events_from_nios{ophid=~\"$OphID\"}[$__range])) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10  CDC customer RPM BloxOne per Ophid ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid) (increase(onprem_cdc_received_events_from_bloxone{ophid=~\"$OphID\"}[$__range]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid) (increase(onprem_cdc_received_events_from_bloxone{ophid=~\"$OphID\"}[$__range])) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC customer RPM NIOS per Ophid and Destination",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid, destination) (increase(onprem_cdc_received_events_from_nios{ophid=~\"$OphID\", destination!=\"\"}[$__range]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid, destination) (increase(onprem_cdc_received_events_from_nios{ophid=~\"$OphID\", destination!=\"\"}[$__range])) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10  CDC customer RPM BloxOne per Ophid and Destination",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid, destination) (increase(onprem_cdc_received_events_from_bloxone{ophid=~\"$OphID\", destination!=\"\"}[$__range]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(\n  10,\n  sum by (account_id, ophid, destination) (increase(onprem_cdc_received_events_from_bloxone{ophid=~\"$OphID\", destination!=\"\"}[$__range])) / $__range_s\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}