{
 "title": "CDC Onprem Resource Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\"},account_id)"
    }
   },
   {
    "name": "ophid",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\", account_id=~\"$account_id\"},ophid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU & Memory Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CDC Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(onprem_container_cpu_usage_seconds_total{account_id=~\"$account_id\", ophid=\"$ophid\",onprem_namespace=\"infoblox\",onprem_pod=~\"cdc.*\"}[3m])",
     "legendFormat": "{{onprem_pod}} , {{onprem_container}}"
    }
   ]
  },
  {
   "title": "CDC Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "onprem_container_memory_working_set_bytes{account_id=~\"$account_id\", ophid=\"$ophid\",onprem_namespace=\"infoblox\",onprem_pod=~\"cdc.*\"}",
     "legendFormat": "{{onprem_pod}} , {{onprem_container}}"
    }
   ]
  },
  {
   "title": "CDC Container Memory Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(onprem_container_memory_working_set_bytes{account_id=~\"$account_id\", ophid=\"$ophid\",onprem_namespace=\"infoblox\",onprem_pod=~\"cdc.*\"} / scalar(sum(onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}))) * 100",
     "legendFormat": "{{onprem_pod}} , {{onprem_container}}"
    }
   ]
  }
 ]
}