{
 "title": "CDC Onprem Events Timeseries",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "Account ID",
    "query": {
     "query": "label_values(onprem_cdc_volume_used_percent,account_id)"
    }
   },
   {
    "name": "ophid",
    "label": "OPHID",
    "query": {
     "query": "label_values(onprem_cdc_volume_used_percent{account_id=~\"$account_id\"},ophid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CDC Onprem Flow Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accepted vs Drained Events Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"onprem_cdc_accepted.*\",account_id=~\"$account_id\",ophid=~\"$ophid\",service_id=~\"infra.*\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")[1m:])/60",
     "legendFormat": "{{name_label}}"
    },
    {
     "expr": "-rate(label_replace({__name__=~\"onprem_cdc_drained.*\",account_id=~\"$account_id\",ophid=~\"$ophid\",service_id=~\"infra.*\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")[1m:])/60",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Accepted vs Drained Events Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(label_replace({__name__=~\"onprem_cdc_accepted.*\",account_id=~\"$account_id\",ophid=~\"$ophid\",service_id=~\"infra.*\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")[1m:])",
     "legendFormat": "{{name_label}}"
    },
    {
     "expr": "-idelta(label_replace({__name__=~\"onprem_cdc_drain.*\",account_id=~\"$account_id\",ophid=~\"$ophid\",service_id=~\"infra.*\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")[1m:])",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Processed Events Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"onprem_cdc_processed.*\",account_id=~\"$account_id\",ophid=~\"$ophid\",service_id=~\"infra.*\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")[1m:])",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Pending Events Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"onprem_cdc_pending.*\",account_id=~\"$account_id\",ophid=~\"$ophid\",service_id=~\"infra.*\"},\"name_label\",\"$1\",\"__name__\",\"(.+)\")[1m:])",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "DNS Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DNS Cloud Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(onprem_cdc_accepted_dns_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Accepted"
      },
      {
       "expr": "rate(onprem_cdc_received_dns_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Received"
      },
      {
       "expr": "-rate(onprem_cdc_drained_dns_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Drained"
      },
      {
       "expr": "-rate(onprem_cdc_filtered_dns_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Filtered"
      }
     ]
    },
    {
     "title": "DNS Reporting Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(onprem_cdc_accepted_dns_reporting_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Accepted"
      },
      {
       "expr": "-rate(onprem_cdc_drained_dns_reporting_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Drained"
      },
      {
       "expr": "rate(onprem_cdc_received_dns_reporting_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Received"
      },
      {
       "expr": "-rate(onprem_cdc_filtered_dns_reporting_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Filtered"
      }
     ]
    }
   ]
  },
  {
   "title": "RPZ Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPZ Cloud Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(onprem_cdc_accepted_rpz_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Accepted"
      },
      {
       "expr": "-rate(onprem_cdc_drained_rpz_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Drained"
      },
      {
       "expr": "rate(onprem_cdc_received_rpz_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Received"
      },
      {
       "expr": "-rate(onprem_cdc_filtered_rpz_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Filtered"
      }
     ]
    }
   ]
  },
  {
   "title": "IPMeta Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IPMeta Cloud Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(onprem_cdc_accepted_ipmeta_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Accepted"
      },
      {
       "expr": "-rate(onprem_cdc_drained_ipmeta_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Drained"
      },
      {
       "expr": "rate(onprem_cdc_received_ipmeta_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Received"
      },
      {
       "expr": "-rate(onprem_cdc_filtered_ipmeta_cloud_events{account_id=~\"$account_id\", ophid=~\"$ophid\"}[1m])/60",
       "legendFormat": "Filtered"
      }
     ]
    }
   ]
  }
 ]
}