{
 "title": "CDC-Flow Timeseries",
 "tags": [
  "cdc",
  "flow",
  "monitoring",
  "timeseries"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "API Request Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS (Queries Per Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_method) (irate(grpc_server_started_total{app=\"cdc-flow\"}[$__interval]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total CPU Usage of CDC Flow Container per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"cdc-flow\", container=\"cdc-flow-api\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"cdc-flow\", container=\"cdc-flow-api\",resource=\"cpu\"})",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"cdc-flow\", container=\"cdc-flow-api\",resource=\"cpu\"})",
     "legendFormat": "CPU limits"
    }
   ]
  },
  {
   "title": "Memory Usage of CDC Flow Container per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"cdc-flow\", container=\"cdc-flow-api\", pod=~\"cdc-flow-.+\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"cdc-flow\", container=\"cdc-flow-api\",resource=\"memory\"})",
     "legendFormat": "memory limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"cdc-flow\", container=\"cdc-flow-api\",resource=\"memory\"})",
     "legendFormat": "memory requests"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100*sum(rate(nginx_ingress_controller_requests{namespace=\"cdc-flow\", status=~\"4[0-9][0-9]\", service=\"cdc-flow-api\"}[$__interval])) / \n (sum(rate(nginx_ingress_controller_requests{namespace=\"cdc-flow\", service=\"cdc-flow-api\"}[$__interval]))>0) or vector(0))",
     "legendFormat": "API requests"
    }
   ]
  },
  {
   "title": "All Errors from Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{app=\"cdc-flow\", grpc_code!=\"OK\"}[$__interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100*sum(rate(nginx_ingress_controller_requests{namespace=\"cdc-flow\", service=\"cdc-flow-api\", status=~\"5[0-9][0-9]\"}[$__interval])) / (sum(rate(nginx_ingress_controller_requests{namespace=\"cdc-flow\", service=\"cdc-flow-api\"}[$__interval]))>0) or vector(0))",
     "legendFormat": "API requests"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Unable to Fulfill",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{app=\"cdc-flow\", grpc_code!~\"OK|Unauthenticated|PermissionDenied|InvalidArgument|NotFound|Unknown\"}[$__interval]))/(sum(rate(grpc_server_handled_total{app=\"cdc-flow\"}[$__interval]))>0)*100) or vector (0)",
     "legendFormat": "All methods"
    }
   ]
  },
  {
   "title": "Service Down (HTTP Status 5xx from Ingress Controller)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(nginx_ingress_controller_requests{service=\"cdc-flow-api\",status=~\"5[0-9][0-9]\"}[$__interval]))/(sum (rate(nginx_ingress_controller_requests{service=\"cdc-flow-api\",status!~\"4[0-9][0-9]\"}[$__interval])) > 0)*100) or vector(0)",
     "legendFormat": "cdc-flow"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{namespace=\"cdc-flow\", container=\"cdc-flow-api\", pod=~\"cdc-flow-.+\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}