{
 "title": "CDC Onprem Resources Alert",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10m",
 "panels": [
  {
   "title": "CDC Onprem Memory Usage Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(onprem_host_memory_usage_used{}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) / \n  (onprem_host_memory_usage_total{}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) * 100",
     "legendFormat": "{{ophid}}"
    }
   ]
  },
  {
   "title": "CDC Onprem CPU Usage Alert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(onprem_cpu_percentage{}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})",
     "legendFormat": "{{ophid}}"
    }
   ]
  },
  {
   "title": "CDC Onprem Volume Usage Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(onprem_cdc_volume_used_percent{}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})",
     "legendFormat": "{{ophid}} - {{device}}"
    }
   ]
  }
 ]
}