{
 "title": "CDC Onprem Resources Tables",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "account id",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\"},account_id)"
    }
   },
   {
    "name": "ophid",
    "label": "ophid",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\", account_id=~\"$account_id\"},ophid)"
    }
   },
   { "name": "memory_threshold", "label": "Memory Threshold %", "query": "1,50,70,90" },
   { "name": "cpu_threshold", "label": "CPU Threshold %", "query": "1,50,70,90" },
   { "name": "disk_threshold", "label": "Volume Threshold %", "query": "1,50,70,90" }
  ]
 },
 "panels": [
  {
   "title": "CDC Onprem Services Summary",
   "type": "stat",
   "description": "Summary of onprem hosts with CDC services",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"}))",
     "legendFormat": "Total Hosts"
    },
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"} == 1))",
     "legendFormat": "Active Hosts"
    },
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"} == 0))",
     "legendFormat": "Inactive Hosts"
    }
   ]
  },
  {
   "title": "Onprem Hosts with Memory Usage > $memory_threshold% (CDC Service)",
   "type": "table",
   "description": "Shows all onprem hosts with memory usage > $memory_threshold% and CDC service running",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) /\n(onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) *100 > $memory_threshold",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} and on(ophid) ((onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) / (onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) * 100 > $memory_threshold)"
    },
    {
     "expr": "onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} and on(ophid) ((onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) / (onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) * 100 > $memory_threshold)"
    }
   ]
  },
  {
   "title": "Onprem Hosts with CPU Usage > $cpu_threshold% (CDC Service)",
   "type": "table",
   "description": "Shows all onprem hosts with CPU usage > $cpu_threshold% and CDC service running",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) > $cpu_threshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onprem Hosts with Volume Usage > $disk_threshold% (CDC Service)",
   "type": "table",
   "description": "Shows all onprem hosts with volume/disk usage > $disk_threshold% and CDC service running",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(onprem_cdc_volume_used_percent{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) > $disk_threshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 20 Hosts with Increasing Memory Usage (Last 3h, CDC Service)",
   "type": "table",
   "description": "Shows hosts with continuously increasing memory usage in the last 3 hours and CDC service running",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20,(rate(onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"}[5m]) / onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"}) * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} > 0.001)",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} / onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * 100 * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}"
    }
   ]
  },
  {
   "title": "Top 20 Hosts with Increasing CPU Usage (Last 3h, CDC Service)",
   "type": "table",
   "description": "Shows hosts with continuously increasing CPU usage in the last 3 hours and CDC service running",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20, rate((onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})[3h:10m]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}"
    }
   ]
  },
  {
   "title": "Top 20 Hosts with Increasing Volume Usage (Last 3h, CDC Service)",
   "type": "table",
   "description": "Shows hosts with continuously increasing volume/disk usage in the last 3 hours and CDC service running",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20, rate((onprem_cdc_volume_used_percent{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})[3h:10m]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_cdc_volume_used_percent{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}"
    }
   ]
  },
  {
   "title": "All Onprem Hosts with CDC Service",
   "type": "table",
   "description": "Shows all onprem hosts running CDC services",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CDC Customers Summary",
   "type": "stat",
   "description": "Summary of customers with CDC services",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(account_id) (onprem_host_service_status{service=~\"cdc.*\"}))",
     "legendFormat": "Total Customers"
    },
    {
     "expr": "count(count by(account_id) (onprem_cdc_received_events_from_bloxone{source=\"bloxone\"}))",
     "legendFormat": "CDC Customers with BloxOne Source"
    },
    {
     "expr": "count(count by(account_id) (onprem_cdc_received_events_from_nios))",
     "legendFormat": "CDC Customers with NIOS Source"
    },
    {
     "expr": "count(\n  (\n    count by(account_id) (onprem_cdc_received_events_from_bloxone{source=\"bloxone\"})\n    * on(account_id)\n    count by(account_id) (onprem_cdc_received_events_from_nios)\n  ) > 0\n)",
     "legendFormat": "CDC Customers with BloxOne & NIOS Sources"
    },
    {
     "expr": "count(\n  count by(account_id) (onprem_host_service_status{service=~\"cdc.*\"})\n  unless\n  (\n    count by(account_id) (onprem_cdc_received_events_from_bloxone{source=\"bloxone\"})\n    or\n    count by(account_id) (onprem_cdc_received_events_from_nios)\n  )\n)",
     "legendFormat": "CDC Customers with No Active Flows"
    }
   ]
  }
 ]
}