{
 "title": "CDC Log Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CDC Flume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_flume\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Flume Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_flume\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Grpc Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_grpc_out\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Grpc Out Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_grpc_out\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Grpc In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_grpc_in\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Grpc In Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_grpc_in\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_agent\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Agent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_agent\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Dns In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_dns_in\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Dns In Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_dns_in\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Ipmeta In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_ipmeta_in\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Ipmeta In Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_ipmeta_in\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Rpz In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_rpz_in\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Rpz In Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_rpz_in\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Splunkcloud",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_splunkcloud_out\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Splunkcloud out Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_splunkcloud_out\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Splunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_splunk_out\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Splunk out Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_splunk_out\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Reporting out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_reporting_out\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Reporting out Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_reporting_out\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Siem out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_siem_out\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Siem out Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_siem_out\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC Http out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "count(rate({containerId=\"cdc_http_out\"} |= \"error\" [1h])) by (containerId, errorType)"
    }
   ]
  },
  {
   "title": "CDC Http out Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "{containerId=\"cdc_http_out\"} |= `error`"
    }
   ]
  },
  {
   "title": "CDC flow Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "{cluster=\"prd-1\", namespace=\"cdc-flow\"}"
    }
   ]
  },
  {
   "title": "CDC flow  Hostapp sync Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "{cluster=\"prd-1\", namespace=\"cdc-flow\", container=\"cdc-flow-hostapp-sync\"} |~ `error`"
    }
   ]
  },
  {
   "title": "Data Exporter Kafka Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "{cluster=\"prd-1\", namespace=\"data-exporter-kafka\", container=\"data-exporter-kafka\"} |~ `error`"
    }
   ]
  },
  {
   "title": "cdc data flow Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "{cluster=\"prd-1\", namespace=\"cdc-data-flow\"} |~ `error`"
    }
   ]
  },
  {
   "title": "CDC Reporting status",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "{cluster=\"prd-1\", namespace=\"cdc-flow\", pod=~\"cdc-status-reporter.*\" }"
    }
   ]
  }
 ]
}