{
 "title": "Onprem host status",
 "tags": [ "support" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ophid",
    "query": "25c9b25fce1efefd8afee97c9fcc332f"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Host composite status(Platform + app_infra + apps)",
   "type": "timeseries",
   "description": "| Values |    description of state\n|------- |----------------------------------\n|    0   | Review Details              \n|    1   | Online           \n|    3   | Pending          \n|    4   | Awaiting Approval ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "onprem_host_composite_status{ophid=\"$ophid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Host Infra status( Platform+App Infra)",
   "type": "timeseries",
   "description": "| Values |   string literal  |  description of state\n|------- |-------------------|----------------------------------\n|    0   | Error             | Both platform and app-management are unhealthy\n|    1   | Online            | Both platform and app-management are healthy\n|    2   | Degraded          | Either one of platform and app-management is unhealthy\n|    3   | Pending           | New and unregistered hosts\n|    4   | Awaiting approval | Hosts waiting for approval\n|    8   | Offline          | ost registered to csp but platform/app management components yet to start",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "onprem_host_infra_status{ophid=\"$ophid\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Service Desired State",
   "type": "timeseries",
   "description": "Shows whether the desired service state is start/stop\n\n| Values | State\n|--------|-------------|\n| 0 |  Stop\n| 1 |  Start",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "min(hostapp_onprem_host_service_desired_state{ophid=\"$ophid\"}) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Current Service Status",
   "type": "timeseries",
   "description": "Shows the current service state \n| Values | State\n|--------|-------------|\n| 0 |  Stop/Down\n| 1 |  Running",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "onprem_host_service_status{ophid=\"$ophid\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Host Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "Shows the % memory utilization of a host",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (onprem_host_memory_usage_used{ophid=\"$ophid\"}/onprem_host_memory_usage_total{ophid=\"$ophid\"}) ",
     "legendFormat": "{{host}} | {{ophid}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows the Total and Used memory of host in GB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "onprem_host_memory_usage_used{ophid=\"$ophid\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "onprem_host_memory_usage_total{ophid=\"$ophid\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Usage % ",
   "type": "timeseries",
   "description": "Disk space used% per file system/mount point on the host ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "onprem_disk_space_used{file_system!~\"overlay.*\",mount_point=~\"/media/root-ro|/media/root-rw|/|/rw|/ro|/storage\",ophid=\"$ophid\"} * 100 / onprem_disk_space_total{file_system!~\"overlay.*\",mount_point=~\"/media/root-ro|/media/root-rw|/|/rw|/ro|/storage\",ophid=\"$ophid\"} ",
     "legendFormat": "{{file_system}} - {{mount_point}}"
    }
   ]
  },
  {
   "title": "Total & Used Disk (GB)",
   "type": "timeseries",
   "description": "Total & Used Disk space in GB per file system/mount point on the host ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "onprem_disk_space_used{file_system!~\"overlay.*\",mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\",ophid=\"$ophid\"}/ (1024 * 1024)",
     "legendFormat": "Used - {{file_system}} - {{mount_point}}"
    },
    {
     "expr": "onprem_disk_space_total{ophid=\"$ophid\",mount_point=~\"/media/root-ro|/media/root-rw|/|/rw|/ro|/storage\"} / (1024 * 1024)",
     "legendFormat": "Total - {{file_system}} - {{mount_point}}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "Combined CPU Usage %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "onprem_host_cpu_percentage_combined{ophid=\"$ophid\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "description": "CPU Usage % per Core",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "(onprem_host_cpu_percentage{ophid=\"$ophid\"})",
     "legendFormat": "{{cpu_id}}"
    }
   ]
  }
 ]
}