{
 "title": "CDC Onprem Resource Table",
 "tags": [
  "cdc",
  "onprem",
  "resources",
  "merged"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "account id",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\"},account_id)"
    }
   },
   {
    "name": "ophid",
    "label": "ophid",
    "query": {
     "query": "label_values(onprem_host_service_status{service=~\"cdc.*\", account_id=~\"$account_id\"},ophid)"
    }
   },
   { "name": "memory_threshold", "label": "Memory Threshold %", "query": "1,50,70,90" },
   { "name": "cpu_threshold", "label": "CPU Threshold %", "query": "1,50,70,90" },
   { "name": "disk_threshold", "label": "Volume Threshold %", "query": "1,50,70,90" }
  ]
 },
 "panels": [
  {
   "title": "CDC Onprem Resource Monitoring - Merged Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CDC Onprem Services Summary",
   "type": "stat",
   "description": "Summary of onprem hosts with CDC services",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"}))",
     "legendFormat": "Total Hosts"
    },
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"} == 1))",
     "legendFormat": "Active Hosts"
    },
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"} == 0))",
     "legendFormat": "Inactive Hosts"
    }
   ]
  },
  {
   "title": "CDC Customers Summary",
   "type": "stat",
   "description": "Summary of customers with CDC services",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(account_id) (onprem_host_service_status{service=~\"cdc.*\"}))",
     "legendFormat": "Total Customers"
    },
    {
     "expr": "count(count by(account_id) (onprem_cdc_received_events_from_bloxone{source=\"bloxone\"}))",
     "legendFormat": "BloxOne Source"
    },
    {
     "expr": "count(count by(account_id) (onprem_cdc_received_events_from_nios))",
     "legendFormat": "NIOS Source"
    }
   ]
  },
  {
   "title": "Hosts with ONLY BloxOne",
   "type": "stat",
   "description": "Summary of hosts with ONLY BloxOne events (no NIOS events)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) unless count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}))",
     "legendFormat": "Total BloxOne Only"
    },
    {
     "expr": "count((count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) unless count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"})) * on(ophid) group_left(service) (onprem_host_service_status{service=~\"cdc.*\"} == 1))",
     "legendFormat": "Active BloxOne Only"
    },
    {
     "expr": "count((count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) unless count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"})) * on(ophid) group_left(service) (onprem_host_service_status{service=~\"cdc.*\"} == 0))",
     "legendFormat": "Inactive BloxOne Only"
    }
   ]
  },
  {
   "title": "Hosts with ONLY NIOS",
   "type": "stat",
   "description": "Summary of hosts with ONLY NIOS (no BloxOne events)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}) unless count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}))",
     "legendFormat": "Total NIOS Only"
    },
    {
     "expr": "count((count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}) unless count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"})) * on(ophid) group_left(service) (onprem_host_service_status{service=~\"cdc.*\"} == 1))",
     "legendFormat": "Active NIOS Only"
    },
    {
     "expr": "count((count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}) unless count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"})) * on(ophid) group_left(service) (onprem_host_service_status{service=~\"cdc.*\"} == 0))",
     "legendFormat": "Inactive NIOS Only"
    }
   ]
  },
  {
   "title": "Hosts with BOTH BloxOne & NIOS",
   "type": "stat",
   "description": "Summary of hosts with BOTH BloxOne AND NIOS events",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) and count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}))",
     "legendFormat": "Total Both Sources"
    },
    {
     "expr": "count((count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) and count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"})) * on(ophid) group_left(service) (onprem_host_service_status{service=~\"cdc.*\"} == 1))",
     "legendFormat": "Active Both Sources"
    },
    {
     "expr": "count((count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) and count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"})) * on(ophid) group_left(service) (onprem_host_service_status{service=~\"cdc.*\"} == 0))",
     "legendFormat": "Inactive Both Sources"
    }
   ]
  },
  {
   "title": "CDC Hosts with No Events",
   "type": "stat",
   "description": "Summary of CDC hosts with no events (neither BloxOne nor NIOS)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"}) unless (count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) or count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"})))",
     "legendFormat": "Total No Events"
    },
    {
     "expr": "count((count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"}) unless (count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) or count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}))) == 1)",
     "legendFormat": "Active No Events"
    },
    {
     "expr": "count((count by(ophid) (onprem_host_service_status{account_id=~\"$account_id\", ophid=~\"$ophid\", service=~\"cdc.*\"}) unless (count by(ophid) (onprem_cdc_received_events_from_bloxone{account_id=~\"$account_id\", ophid=~\"$ophid\", source=\"bloxone\"}) or count by(ophid) (onprem_cdc_received_events_from_nios{account_id=~\"$account_id\", ophid=~\"$ophid\"}))) == 0)",
     "legendFormat": "Inactive No Events"
    }
   ]
  },
  {
   "title": "Onprem Hosts with Memory Usage > $memory_threshold% (CDC Service)",
   "type": "table",
   "description": "Shows all onprem hosts with memory usage > $memory_threshold% and CDC service running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) /\n(onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) *100 > $memory_threshold",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} and on(ophid) ((onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) / (onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) * 100 > $memory_threshold)"
    },
    {
     "expr": "onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} and on(ophid) ((onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) / (onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) * 100 > $memory_threshold)"
    }
   ]
  },
  {
   "title": "Onprem Hosts with CPU Usage > $cpu_threshold%",
   "type": "table",
   "description": "Shows all onprem hosts with CPU usage > $cpu_threshold% and CDC service running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"}) > $cpu_threshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onprem Hosts with Volume Usage > $disk_threshold%",
   "type": "table",
   "description": "Shows all onprem hosts with volume/disk usage > $disk_threshold% and CDC service running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(onprem_disk_space_used{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * 100 / onprem_disk_space_total{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) > $disk_threshold",
     "legendFormat": "__auto"
    },
    {
     "expr": "(onprem_disk_space_total{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} / (1024 * 1024)) * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} and on(ophid) ((onprem_disk_space_used{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * 100 / onprem_disk_space_total{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) > $disk_threshold)"
    },
    {
     "expr": "(onprem_disk_space_used{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} / (1024 * 1024)) * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} and on(ophid) ((onprem_disk_space_used{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * 100 / onprem_disk_space_total{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}) > $disk_threshold)"
    }
   ]
  },
  {
   "title": "Top 20 Memory Rate of Increase",
   "type": "table",
   "description": "Shows hosts with continuously increasing memory usage in the last 3 hours and CDC service running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20,(rate(onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"}[5m]) / onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"}) * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"} > 0.001)",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_host_memory_usage_used{account_id=~\"$account_id\", ophid=~\"$ophid\"} / onprem_host_memory_usage_total{account_id=~\"$account_id\", ophid=~\"$ophid\"} * 100 * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}"
    }
   ]
  },
  {
   "title": "Top 20 CPU Rate of Increase",
   "type": "table",
   "description": "Shows hosts with continuously increasing CPU usage in the last 3 hours and CDC service running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20, rate((onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"}\n  * on(ophid) group_left(service)\n  onprem_host_service_status{service=~\"cdc.*\"})[3h:10m]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_cpu_percentage{account_id=~\"$account_id\", ophid=~\"$ophid\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}"
    }
   ]
  },
  {
   "title": "Top 20 Volume Rate of Increase",
   "type": "table",
   "description": "Shows hosts with continuously increasing volume/disk usage in the last 3 hours and CDC service running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20, rate((onprem_disk_space_used{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * 100 / onprem_disk_space_total{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"})[3h:10m]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "onprem_disk_space_used{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * 100 / onprem_disk_space_total{account_id=~\"$account_id\", ophid=~\"$ophid\", file_system!~\"overlay.*\", mount_point=~\"/media/root-rw|/|/rw|/ro|/storage\"} * on(ophid) group_left(service) onprem_host_service_status{service=~\"cdc.*\"}"
    }
   ]
  }
 ]
}