{
 "title": "CDC Cloud to Cloud Timeseries",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_status",
    "label": "Pod Status",
    "query": "Running, Pending, Succeeded, Failed, Unknown"
   },
   {
    "name": "account_id",
    "label": "Account ID",
    "query": "label_values(kube_pod_info{namespace=\"cdc-data-flow\"}, pod)"
   },
   {
    "name": "flow_id",
    "label": "Flow ID",
    "query": "label_values(kube_pod_info{namespace=\"cdc-data-flow\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory & CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"cdc-data-flow\", pod=~\".*-${account_id}-${flow_id}-.*\"}[2m])) by (pod, container)) * 100",
     "legendFormat": "{{pod}}, {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=\"cdc-data-flow\", pod=~\".*-${account_id}-${flow_id}-.*\"}) by (pod, container)) / (sum(container_spec_memory_limit_bytes{namespace=\"cdc-data-flow\", pod=~\".*-.*-.*-.*\"}) by (pod, container)) * 100",
     "legendFormat": "{{pod}}, {{container}}"
    }
   ]
  },
  {
   "title": "Pod Status & Restart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cdc-data-flow Pod Restart Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"cdc-data-flow\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Status - $pod_status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"cdc-data-flow\", phase=~\"$pod_status\", pod=~\".*-${account_id}-${flow_id}-.*\"}) by (pod, phase)",
     "legendFormat": "{{pod}}: {{phase}}"
    }
   ]
  },
  {
   "title": "Configmaps & Statefulsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "StatefulSet Ready Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=\"cdc-data-flow\", statefulset=~\".*-${account_id}-${flow_id}\"}) by (statefulset)",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "ConfigMaps Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_configmap_info{namespace=\"cdc-data-flow\", configmap=~\".*-${account_id}-${flow_id}\"}) by (configmap)",
     "legendFormat": "{{configmap}}"
    }
   ]
  },
  {
   "title": "Network Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"cdc-data-flow\", pod=~\".*-${account_id}-${flow_id}-.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"cdc-data-flow\", pod=~\".*-${account_id}-${flow_id}-.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cdc-data-flow Pod Failed Alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_status_phase{namespace=\"cdc-data-flow\", phase=~\"Failed|Pending|Unknown\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage Alert",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"cdc-data-flow\", pod=~\".*-.*-.*-.*\"}[2m])) by (pod, container)) * 100",
     "legendFormat": "{{pod}}, {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage Alert",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=\"cdc-data-flow\", pod=~\".*-.*-.*-.*\"}) by (pod, container)) / (sum(container_spec_memory_limit_bytes{namespace=\"cdc-data-flow\", pod=~\".*-.*-.*-.*\"}) by (pod, container)) * 100",
     "legendFormat": "{{pod}}, {{container}}"
    }
   ]
  }
 ]
}